### ISSUE TITLE
Some of the theme tags are not working

### ISSUE THREAD

**Issue by kevinmu17** [verbb/formie-theme-configs#1]
### Describe the bug

When submitting, the error message is showing, but it has no tailwind classes. This also applies to fieldError, the default fui-* classes are present
```js
 alertError: {
    attributes: {
        class: 'rounded-md bg-red-50 border border-red-200 text-sm text-red-700 p-4 mb-4',
    },
},
```

### Steps to reproduce

1. use https://github.com/verbb/formie-theme-configs/blob/main/tailwind/index.html
2. submit a simple contact form, the error alert is not getting any tailwind classes

### Craft CMS version

Craft Pro 4.2.2

### Plugin version

2.0.7

### Multi-site?

Yes

**Comment by engram-design** [comment]
I imagine your form is Ajax-enabled? Can you confirm? If so, that should be the only case where these classes aren't added.

**Comment by kevinmu17** [comment]
Thats true, i'm using Ajax. So with ajax tailwind isn't working?

**Comment by engram-design** [comment]
It's more that anything that JS does, it isn't currently compatible with Theme Config - at least at the moment. Because when things are Ajax, the success/error messages are created through JS, they need to know about these classes.

Moving to https://github.com/verbb/formie/issues/1060
