### ISSUE TITLE
Consider providing the configs in Plugin Configuration (PHP) format too

### ISSUE THREAD

**Issue by alexr8** [verbb/formie-theme-configs#2]
### What are you trying to do?

Setting Formie up for the first time, I was keen to use the provided tailwind config to get me started, but define it at the plugin configuration level rather than in my templates. 

### What's your proposed solution?

It would be useful to provide a sample of the `formie.php themeConfig` for tailwind (and for bootstrap too) within this repo that can be copy pasted rather than manually reformatting the twig one to php.

**Comment by engram-design** [comment]
Fair enough! It’s not too much work to translate Twig to PHP. Will add it to my list

**Comment by alexr8** [comment]
Amazing thanks @engram-design - one thing i wasn't sure when i was translating was if there was a comparable way of doing these bits in the php themeConfig
```
 buttonWrapper: {
            attributes: {
                class: [
                    'flex justify-start -mx-2',
                    "{{ buttonsPosition == 'right' ? 'justify-end' }}",
                    "{{ buttonsPosition == 'center' ? 'justify-center' }}",
                    "{{ buttonsPosition == 'left-right' ? 'justify-between' }}",
```

**Comment by engram-design** [comment]
Just added those [config files](https://github.com/verbb/formie-theme-configs/commit/4735152395f26ecb42c260721982ea7ab5199604)

As for those, they're exactly the same. They still need to be Twig strings and are evaluated in Twig.

**Comment by alexr8** [comment]
Amazing, thank you!
