### ISSUE TITLE
Bootstrap - Checkboxes - Layout: Horizontal

### ISSUE THREAD

**Issue by svondervoort** [verbb/formie-theme-configs#4]
### Describe the bug

It seems there is no option for the Checkboxes field layout to be viewed horizontally.
If I disable the default bootstrap configuration it works but when enabled the checkboxes are vertical instead of horizontal.
Is something missing in the example template?

### Steps to reproduce

1. Create a form with a checkboxes field
2. Set the appearance - layout option to `horizontal`
3. Use the default Bootstrap theme on the form

### Craft CMS version

4.8.9

### Plugin version

2.1.11

**Comment by engram-design** [comment]
Looks like just forgot to include an example of that. Just updated the [examples](https://github.com/verbb/formie-theme-configs/commit/de5c6114d5534889da18dcf130f9e751f105bd44) to include that conditional.
