### ISSUE TITLE
Tailwind file includes deprecation

### ISSUE THREAD

**Issue by darylknight** [verbb/formie-theme-configs#6]
### Describe the bug

Using the Tailwind template - I'm seeing this in Craft 5:

`craft.formie.getVisibleFields() has been deprecated. Use row.getIsHidden() instead.`

### Steps to reproduce

Use:

```
row: {
    attributes: {
        class: [
            'flex flex-wrap -mx-4 mb-4',
            "{{ not craft.formie.getVisibleFields(row) ? 'hidden' }}",
        ],
    },
},
```

### Craft CMS version

5.2.5

### Plugin version

3.0.0-beta.16

### Multi-site?

No

**Comment by engram-design** [comment]
Good call that I need to create new versions for Formie 3 for Craft 5, I was just planning to do that once out of beta.

**Comment by engram-design** [comment]
Just realised I never got around to updating this. There's a `formie-3` branch with these updates https://github.com/verbb/formie-theme-configs/tree/formie-3/tailwind
